# Use the official MongoDB image from the Docker Hub
FROM mongo:latest

RUN ["apt-get", "update"]
RUN ["apt-get", "install", "-y", "vim"]

# Set environment variables for MongoDB (optional)
ENV MONGO_INITDB_ROOT_USERNAME=admin
ENV MONGO_INITDB_ROOT_PASSWORD=admin

# Expose the MongoDB default port
EXPOSE 27017

# Optionally, copy initialization scripts to set up your MongoDB instance
# COPY ./init-scripts /docker-entrypoint-initdb.d/

# Default command to run MongoDB
CMD ["mongod"]
