services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: nafrin/python-backend
    ports:
      - "5001:5001"
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: nafrin/python-frontend
    ports:
      - "5000:5000"
    depends_on:
      - backend

  mongodb:
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    image: nafrin/python-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
