FROM python:3.9-slim
WORKDIR /app

# Install dependencies
COPY requirements.txt /app/
#RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir -r requirements.txt --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host=files.pythonhosted.org


# Copy application files
COPY . /app/

# Expose the port
EXPOSE 5001

# Start the API
CMD ["python", "api.py"]
