services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.back
    image: nafrin/python-backend
    ports:
      - "5001:5001"
    depends_on:
      - mongodb

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.front
    image: nafrin/python-frontend
    ports:
      - "5000:5000"
    depends_on:
      - backend

  mongodb:
    build:
      context: .
      dockerfile: Dockerfile.mongodb
    image: nafrin/python-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
