apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front
        image: nafrin/python:front-${VERSION}
        ports:
        - containerPort: 5000
        env:
        - name: BACKEND_URL
          value: "http://back:5001"

---
apiVersion: v1
kind: Service
metadata:
  name: front-service
spec:
  selector:
    app: front
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
