front:
  replicas: 1
  image: nafrin/python-frontend
  version: 2.0.0
  port: 5000
  targetPort: 5000
  backendUrl: "http://back:5001"

back:
  replicas: 1
  image: nafrin/python-backend
  version: 2.0.0
  port: 5001
  targetPort: 5001
  mongoUrl: "mongodb://mongo:27017"

mongo:
  replicas: 1
  image: nafrin/python-mongodb
  version: 2.0.0
  port: 27017
  targetPort: 27017 
