front:
  replicas: 1
  image: nafrin/python-frontend
  version: latest
  port: 5000
  backendUrl: "http://back:5001"

back:
  replicas: 1
  image: nafrin/python
  version: latest
  port: 5001
  mongoUrl: "mongodb://mongo:27017"

mongo:
  replicas: 1
  image: mongo
  version: latest
  port: 27017
